#Minecraft server properties
#Thu May 28 16:29:21 CDT 2026
level-name=world
hellworld=false
spawn-monsters=true
max-players=20
server-ip=
online-mode=true
pvp=true
spawn-animals=true
server-port=25565
